[2025-05-15 21:33:08 +0000] [17921] [INFO] Starting gunicorn 23.0.0
[2025-05-15 21:33:08 +0000] [17921] [INFO] Listening at: http://127.0.0.1:8000 (17921)
[2025-05-15 21:33:08 +0000] [17921] [INFO] Using worker: sync
[2025-05-15 21:33:08 +0000] [17922] [INFO] Booting worker with pid: 17922
[2025-05-15 21:33:08 +0000] [17922] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 395, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/www/wwwroot/apiDunas-main/v1/app.py", line 5, in <module>
    from flask import Flask, render_template, request, redirect, url_for, flash, session, jsonify, send_file, Response, stream_with_context
ModuleNotFoundError: No module named 'flask'
[2025-05-15 21:33:09 +0000] [17922] [INFO] Worker exiting (pid: 17922)
[2025-05-15 21:33:09 +0000] [17921] [ERROR] Worker (pid:17922) exited with code 3
[2025-05-15 21:33:09 +0000] [17921] [ERROR] Shutting down: Master
[2025-05-15 21:33:09 +0000] [17921] [ERROR] Reason: Worker failed to boot.
[2025-05-15 21:33:12 +0000] [17923] [INFO] Starting gunicorn 23.0.0
[2025-05-15 21:33:12 +0000] [17923] [INFO] Listening at: http://127.0.0.1:8000 (17923)
[2025-05-15 21:33:12 +0000] [17923] [INFO] Using worker: sync
[2025-05-15 21:33:12 +0000] [17924] [INFO] Booting worker with pid: 17924
[2025-05-15 21:33:12 +0000] [17924] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 395, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/www/wwwroot/apiDunas-main/v1/app.py", line 5, in <module>
    from flask import Flask, render_template, request, redirect, url_for, flash, session, jsonify, send_file, Response, stream_with_context
ModuleNotFoundError: No module named 'flask'
[2025-05-15 21:33:12 +0000] [17924] [INFO] Worker exiting (pid: 17924)
[2025-05-15 21:33:12 +0000] [17923] [ERROR] Worker (pid:17924) exited with code 3
[2025-05-15 21:33:12 +0000] [17923] [ERROR] Shutting down: Master
[2025-05-15 21:33:12 +0000] [17923] [ERROR] Reason: Worker failed to boot.
[2025-05-15 21:38:27 +0000] [18245] [INFO] Starting gunicorn 23.0.0
[2025-05-15 21:38:27 +0000] [18245] [INFO] Listening at: http://127.0.0.1:8000 (18245)
[2025-05-15 21:38:27 +0000] [18245] [INFO] Using worker: sync
[2025-05-15 21:38:27 +0000] [18246] [INFO] Booting worker with pid: 18246
[2025-05-15 21:38:27 +0000] [18246] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 395, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/www/wwwroot/apiDunas-main/v1/app.py", line 5, in <module>
    from flask import Flask, render_template, request, redirect, url_for, flash, session, jsonify, send_file, Response, stream_with_context
ModuleNotFoundError: No module named 'flask'
[2025-05-15 21:38:27 +0000] [18246] [INFO] Worker exiting (pid: 18246)
[2025-05-15 21:38:27 +0000] [18245] [ERROR] Worker (pid:18246) exited with code 3
[2025-05-15 21:38:27 +0000] [18245] [ERROR] Shutting down: Master
[2025-05-15 21:38:27 +0000] [18245] [ERROR] Reason: Worker failed to boot.
